language: ruby
rvm:
  - 2.0.0

services: mongodb

bundler_args: --local

before_script:
  - cp config/config.yml.example config/config.yml

script: rake tests:all

notifications:
  email:
    recipients:
      - eric@sunlightfoundation.com
    on_success: change
    on_failure: change
